### ISSUE TITLE
password mismatch doesnt show error while creating a docker host in azure explorer

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#127]
![image](https://cloud.githubusercontent.com/assets/16231002/23081711/e5f6334e-f50a-11e6-9a2c-a3a69ae0e243.png)

**Comment by arroyc** [comment]
help doesn't pop up any help

![image](https://cloud.githubusercontent.com/assets/16231002/23081751/1adb62e6-f50b-11e6-83b1-0d3bab3bf539.png)

**Comment by milismsft** [comment]
This should be fixed in the latest version.

**Comment by bsaby** [comment]
Test used artifacts/azure-toolkit-for-intellij.215.zip
if password mismatch, clicking "Finish" will bring the tab with the Password input into focus.
But, help still doesn't pop up any help.
![image](https://cloud.githubusercontent.com/assets/22470312/23351561/e0cdba0a-fcfc-11e6-85ac-06125c140338.png)

**Comment by milismsft** [comment]
Help topics are not implemented at the moment... I did change the dialog so if there's a mismatching password, the user will be prompted to the exact input field while the Finish will be disabled until the user attempts to correct the error.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.225.zip
