### ISSUE TITLE
HDInsight DataLake: Failed to get default storage account

### ISSUE THREAD

**Issue by Whoops** [Microsoft/azure-tools-for-java#34]
Attempting to connect to an HDInsight Cluster with DataLake as it's primary storage results in the following exception

```
com.microsoft.azure.hdinsight.sdk.common.HDIException: Failed to get default storage account name
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getDefaultStorageAccount(ClusterDetail.java:225)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getConfigurationInfo(ClusterDetail.java:203)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refresh(StorageAccountFolderNode.java:56)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The same error occurs when attempting to submit a job to Spark. Tested both with Spark 1.X and 2.X

**Comment by martinsawicki** [comment]
@voidfunction yours?

**Comment by voidfunction** [comment]
@martinsawicki Yes and it has been fixed. @Whoops Thanks for your reporting.

**Comment by Whoops** [comment]
Any idea when this will be published? I'm still getting this error on the latest version of both the Eclipse and IntelliJ plugins.

**Comment by martinsawicki** [comment]
the next major update to Eclipse and INtelliJ Toolkits (v3.0) is planned for early April.
