### ISSUE TITLE
[Eclipse][IntelliJ]Cannot found new resource group when creating a redis cache.

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#596]
Repro Step:
1. In Azure  Explorer, right click Redis Cache to create a redis cache.
2. Configure as follow: 
    Resource group: new
    Pricing Tier: P3 Premium
    enable Non-SSL port: Yes
3. Click OK.

**Expected:**
The new redis cache is created successfully.

**Actual:**
An error window pops out.
![aaaa](https://cloud.githubusercontent.com/assets/26756696/26821919/c5f2519c-4ada-11e7-82ae-e4a51723105f.PNG)

**Not regression issue.
Not reproduce every time.**

**Comment by jdneo** [comment]
Fixed, please verify in the new daily build, thanks. @davidliangze

**Comment by davidliangze** [comment]
Still reproduce in build Daily.27. in both IntelliJ and Eclipse on all platforms (Windows, Mac and Linux).

**Comment by jdneo** [comment]
Hi, @davidliangze. I just check in the code today morning. So you can verify this issue in tomorrow's dauly build, thanks.

**Comment by davidliangze** [comment]
Test passed using build Daily.28 in both Eclipse and IntelliJ.
