### ISSUE TITLE
Azure Functions local process not killed properly on Mac/IntelliJ

### ISSUE THREAD

**Issue by justinyoo** [microsoft/azure-tools-for-java#6374]
Hi, Team.

I'm not sure this is the issue from this plugin or IntelliJ itself, but I'd like to create an issue here. Here's my dev environment:

* Mac OS (Monterey; 12.2)
* IntelliJ CE (2021.3.2)
* Azure Tools for IntelliJ 3.61.1 - 2021.3
* Azure Functions Core Tools v4 4.0.3971

Here's how to reproduce the error:

1. Run an Azure Functions app from IntelliJ.
2. Confirm that it takes the port of 7071.
3. Stop the app.
4. Re-run the Azure Functions app from IntelliJ.
5. Confirm that the port 7071 is still occupied by another process.

![image](https://user-images.githubusercontent.com/1538528/152106058-7ea24be3-99b6-4619-8977-162633e42e94.png)

Therefore, in order to re-run the Function app, I have to manually find and kill the process every time. Here's what I use to kill the process:

https://gist.github.com/justinyoo/045201b2c4280c818ca872af6284c720

I google'd whether it's the issue of IntelliJ itself or this plugin, and found these threads:

* https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000763924-My-java-processes-don-t-terminate-so-I-need-to-kill-9-them-
* https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003265560-Unable-to-terminate-sub-process-from-which-I-m-draining-stdout-stderr

Although they're a bit old conversations, apparently other devs are experiencing similar issues. So, I checked the code how it's handled and found it:

https://github.com/microsoft/azure-tools-for-java/blob/52be6ef9f4ce175a7676b16beea3f2f83b9fc7a6/PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-appservice/src/main/java/com/microsoft/azure/toolkit/intellij/legacy/function/runner/localrun/FunctionRunState.java#L413-L417

As I'm not a Java dev, I don't know what the code exactly means. But, I suspect that the code doesn't kill all the child processes. Because Azure Functions runtime takes at least two processes - main for the runtime itself and one sub process for the language worker, when the tool stops the process it should stop all the processes including main and its sub.

it would be great if you can take a look.

**Comment by Flanker32** [comment]
@justinyoo Thanks a lot for your report and investigation, we will looking into this issue, and will update here once there are updates.

**Comment by wcom939** [comment]
This also occurs on Windows

**Comment by justinyoo** [comment]
> This also occurs on Windows

It's not the case to me. I only see this issue on Mac OS.

**Comment by Flanker32** [comment]
@wcom939 Thanks for your information, could you please share some more info like the function core tools and toolkit version?

**Comment by wcom939** [comment]
It occurred for me when closing intellij while not terminating the run dialog. I had to restart my PC to clear it. Running windows 11.

Azure Functions Core Tools
Core Tools Version:       4.0.3971 Commit hash: d0775d487c93ebd49e9c1166d5c3c01f3c76eaaf  (64-bit)
Function Runtime Version: 4.0.1.16815

![image](https://user-images.githubusercontent.com/16446451/155138968-847d29e8-2a24-4339-9bb2-f111fd183611.png)

**Comment by Flanker32** [comment]
@wcom939 Thanks for your report, azure toolkit will run function core tools in a new process and close it when you close terminate the run configuration, but this may not work if you close intellij directly, will investigate how to kill the process in this case.

**Comment by Flanker32** [comment]
@justinyoo Thanks again for your help, this issue should be resolved in the latest release v3.62.0, beside we also support set the func port manually, could you please upgrade to the latest version and try again?

**Comment by braxtonstuart** [comment]
FYI - I am still experiencing these issues on macOS.

IntelliJ IDEA 2022.2.1 Ultimate Edition
Azure Toolkit for Intellij 3.68.0-2022.2

**Azure Functions Core Tools**
Core Tools Version:       4.0.4736 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.8.1.18957

![Screen Shot 2022-09-02 at 3 52 57 PM](https://user-images.githubusercontent.com/599926/188226864-c505f8ba-1535-4dd0-b64a-51509fb0283e.png)

Thanks @justinyoo for the including the bash commands to kill the process... saved me from having to dig up the `lsof` input params.
